model_name: "propension_bajas"

table:
  daily_events: default.daily_events
  train: default.train
  test: default.test
  metrics: default.metrics
  daily_predictions: default.daily_predictions
  daily_features: default.daily_features

modeling:
  seed: 99
  test_size: .2
  feature_cols: ['x1','x2','x3']

